#version: "3"
#
#volumes:
#  postgres_data:
#
#services:
#  db:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
##  db:
##    image: local/postgres
##    build:
##      context: .
##      dockerfile: ./Dockerfile.postgres
##    environment:
##      - POSTGRES_DB=postgres
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=postgres
##    volumes:
##      - postgres_data:/var/lib/postgresql/data
##    ports:
##      - 127.0.0.1:5432:5432
#
##  app:
##    image: local/app
##    build:
##      context: .
##      dockerfile: ./Dockerfile
##    depends_on:
##      - db
##    environment:
##      - BEHIND_PROXY=nginx
##    volumes:
##      - ../../.:/app
#
#  nginx:
#    image: nginx:stable-alpine
##    depends_on:
##      - app
##    environment:
##      - SSL_CERT_FILENAME=_wildcard.secjur.test.pem
##      - SSL_KEY_FILENAME=_wildcard.secjur.test-key.pem
##    volumes:
##      - "D:/certificates:/etc/nginx/certs"
##      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
#    ports:
#      - 127.0.0.1:8000:8000
