name: 'Build and deploy docker image'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Ubuntu-22.04
    steps:
      - uses: TimDaub/hetzner-cloud-deploy-server-action@v2
        with:
          server-name: docker-ce
          server-image: docker-ce
          server-type: CAX11
          ssh-key-name: default
          hcloud-token: HnpUy2b6WqdQJfftl3uQFRj1Uxtgk16hmCqOEsnEvFMs8yvNPXVa6vDg4xAGzmR4
          floating-ip-id: 41712547
          floating-ip-assignment-timeout: 300002
